# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: PR Generator

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: musescore-x86_64

    steps:
    - uses: actions/checkout@v2

    # - name: Update scores folders
    #   run: python ./.github/workflows/updater.py

    # - name: switching from HTTPS to SSH
    #   run: git remote set-url origin ${{ secrets.ssh }}

    # - name: check for changes
    #   run: git status

    # - name: stage changed files
    #   run: git add .

    # - name: commit changed files
    #   run: git commit -m "Auto update"

    # - name: fetch from master
    #   run: git fetch origin master

    # - name: push code to master
    #   run: git push origin HEAD:master
