# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Score sheet convertor

on: [pull_request]

jobs:
  score_sheet_exporter:
    runs-on: ubuntu-latest
    name: A job to convert score sheets

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout 
        uses: actions/checkout@v2

      - name: Get branch name
        uses: mdecoleman/pr-branch-name@1.0.0  #
        id: vars
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get changed files
        id: files
        uses: jitterbit/get-changed-files@v1
        with:
          # Format of the steps output context.
          # Can be 'space-delimited', 'csv', or 'json'.
          # Default: 'space-delimited'
          format: 'space-delimited'

      - name: Convert score to images
        uses: ./ # Uses an action in the root directory
        id: convert
        with:
          diff-files: ${{ steps.files.outputs.added_modified }}

      - uses: gr2m/create-or-update-pull-request-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.CREATE_UPDATE_PR_ACTION_TOKEN }}
        with:
          author: "Exporter bot <no-reply@kray.me>"
          branch: ${{ steps.vars.outputs.branch }}
          commit-message: "Auto-generated files"
